# Generated by Django 5.2.8 on 2025-11-21 21:34

import django.db.models.deletion
import parking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking_type', models.CharField(choices=[('hourly', 'Почасовая'), ('daily', 'Суточная'), ('night', 'Ночная'), ('weekly', 'Недельная'), ('monthly', 'Месячная')], default='hourly', max_length=16, verbose_name='Тип бронирования')),
                ('start_at', models.DateTimeField(verbose_name='Начало брони')),
                ('end_at', models.DateTimeField(verbose_name='Окончание брони')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждена'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='pending', max_length=16, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость, ₽')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('external_payment_id', models.CharField(blank=True, help_text='Связка с платежом у провайдера (например, YooKassa payment_id).', max_length=64, verbose_name='ID платежа провайдера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('parking_type', models.CharField(choices=[('yard', 'Дворовая парковка'), ('underground', 'Подземная парковка'), ('multilevel', 'Многоуровневая парковка'), ('street', 'Уличная парковка'), ('office', 'Офисная парковка'), ('home', 'Домашнее место')], default='yard', max_length=32, verbose_name='Тип парковки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', parking.models.PointField(blank=True, null=True, verbose_name='Точка на карте')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_approved', models.BooleanField(default=False, help_text='Одобряется администратором перед публикацией.', verbose_name='Одобрен модерацией')),
                ('is_private', models.BooleanField(default=False, help_text='Если включено, объект виден только по прямым ссылкам/владельцу.', verbose_name='Приватный')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Объект парковки',
                'verbose_name_plural': 'Объекты парковки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, verbose_name='Название/номер места')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('vehicle_type', models.CharField(choices=[('car', 'Легковой автомобиль'), ('moto', 'Мотоцикл'), ('commercial', 'Коммерческий транспорт')], default='car', max_length=16, verbose_name='Тип транспорта')),
                ('is_covered', models.BooleanField(default=False, verbose_name='Крытое место')),
                ('has_ev_charging', models.BooleanField(default=False, verbose_name='Есть зарядка')),
                ('is_24_7', models.BooleanField(default=True, verbose_name='Круглосуточно')),
                ('max_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Максимальная высота (м)')),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час, ₽')),
                ('nightly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за ночь, ₽')),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за сутки, ₽')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена за месяц, ₽')),
                ('allow_dynamic_pricing', models.BooleanField(default=False, help_text='Если включено, тариф может корректироваться рекомендациями AI.', verbose_name='Динамическая цена (AI)')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно')], default='active', max_length=16, verbose_name='Статус')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.parkinglot', verbose_name='Объект парковки')),
            ],
            options={
                'verbose_name': 'Парковочное место',
                'verbose_name_plural': 'Парковочные места',
                'ordering': ('lot__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.CharField(choices=[('foreign_car', 'Чужая машина на месте'), ('no_show', 'Пользователь не приехал'), ('no_free_spot', 'Не нашёл свободного места'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='parking.booking', verbose_name='Бронирование')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='parking.parkingspot', verbose_name='Парковочное место')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='parking.parkingspot', verbose_name='Парковочное место'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('desired_start', models.DateTimeField(verbose_name='Желаемое начало')),
                ('desired_end', models.DateTimeField(verbose_name='Желаемое окончание')),
                ('auto_book', models.BooleanField(default=False, help_text='Если включено, при освобождении места будет создана бронь автоматически.', verbose_name='Авто‑бронирование')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('notified', 'Уведомлён'), ('booked', 'Авто‑бронирование создано'), ('cancelled', 'Отменено')], default='waiting', max_length=16, verbose_name='Статус')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='parking.parkingspot', verbose_name='Парковочное место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись в листе ожидания',
                'verbose_name_plural': 'Лист ожидания',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'spot', 'desired_start', 'desired_end')},
            },
        ),
    ]
