# Generated by Django 5.2.8 on 2025-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='stress_index',
            field=models.FloatField(default=0.0, help_text='Средняя загруженность мест за последние 7 дней. Обновляется фоновыми задачами AI.', verbose_name='Индекс загруженности (0..1)'),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='occupancy_7d',
            field=models.FloatField(default=0.0, help_text='Доля времени, когда место было занято за последние 7 дней. Обновляется фоновыми задачами AI.', verbose_name='Загруженность за 7 дней (0..1)'),
        ),
    ]
