# Generated by Django 5.2.8 on 2025-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_billing_mode_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkinglot',
            name='parkinglot_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingspot',
            name='spot_status_ev_cov_idx',
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
