# Generated by Django 5.2.8 on 2025-11-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider', models.CharField(choices=[('yookassa', 'YooKassa')], default='yookassa', max_length=32, verbose_name='Провайдер')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='ID платежа у провайдера')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает оплаты'), ('succeeded', 'Успешен'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], db_index=True, default='created', max_length=16, verbose_name='Статус')),
                ('success', models.BooleanField(default=False, verbose_name='Успешен')),
                ('failure', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('raw_response', models.JSONField(blank=True, help_text='Сырые данные, вернувшиеся при создании платежа.', null=True, verbose_name='Ответ провайдера')),
                ('raw_webhook', models.JSONField(blank=True, help_text='Последнее уведомление провайдера по этому платежу.', null=True, verbose_name='Последний webhook')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.booking', verbose_name='Бронь')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
