# Generated by Django 5.2.8 on 2025-11-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('yookassa', 'YooKassa'), ('stripe', 'Stripe')], default='yookassa', max_length=32, verbose_name='Провайдер'),
        ),
    ]
