# Generated by Django 5.2.8 on 2025-12-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d9fb24_idx',
            old_name='core_audit_action_6abf09_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_target__6c66b3_idx',
            old_name='core_audit_target__e9a95a_idx',
        ),
    ]
