# Generated by Django 5.2.8 on 2025-11-23 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Используется только для поиска и проверки уникальности email.', max_length=64, verbose_name='Хэш нормализованного email'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Используется только для поиска и проверки уникальности телефона.', max_length=64, verbose_name='Хэш нормализованного телефона'),
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон')], max_length=16, verbose_name='Канал')),
                ('purpose', models.CharField(choices=[('register', 'Регистрация'), ('login', 'Вход'), ('reset_password', 'Сброс пароля')], max_length=32, verbose_name='Назначение')),
                ('code_hash', models.CharField(db_index=True, max_length=128, verbose_name='Хэш кода')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_lo_user_id_024bc5_idx')],
            },
        ),
    ]
