# Generated by ChatGPT on 2025-12-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_mfa_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_mfa_change",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Последнее изменение MFA",
                help_text="Используется для инвалидирования сессий и токенов после изменения MFA.",
            ),
        ),
    ]
