# Generated by Django 5.2.8 on 2025-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_last_mfa_change'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='accounts_so_provide_98721f_idx',
            old_name='accounts_so_provide_3a0cdb_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='accounts_so_user_id_0a462a_idx',
            old_name='accounts_so_user_id_3f2c3e_idx',
        ),
        migrations.AlterField(
            model_name='logincode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Регистрация'), ('login', 'Вход'), ('reset_password', 'Сброс пароля'), ('mfa', 'MFA подтверждение')], max_length=32, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
