# Generated by hand to add AuthIdentity and user display/timestamps

import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_accounts_so_provide_3a0cdb_idx_accounts_so_provide_98721f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Используется в UI вместо username, если указано.",
                max_length=255,
                verbose_name="Отображаемое имя",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.CreateModel(
            name="AuthIdentity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("email_magic", "Email magic link/code"), ("phone_sms", "Phone SMS"), ("vk", "VK"), ("yandex", "Yandex"), ("google", "Google")], max_length=32, verbose_name="Провайдер")),
                ("provider_user_id", models.CharField(help_text="Например email/телефон или внешний id", max_length=255, verbose_name="ID пользователя у провайдера")),
                ("access_token", django_cryptography.fields.encrypt(models.TextField(blank=True, help_text="Минимально необходимый токен; хранится шифрованно.", null=True, verbose_name="Access token"))),
                ("refresh_token", django_cryptography.fields.encrypt(models.TextField(blank=True, help_text="Опционально, хранится шифрованно.", null=True, verbose_name="Refresh token"))),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Истекает")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Доп. данные")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("user", models.ForeignKey(on_delete=models.CASCADE, related_name="auth_identities", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь")),
            ],
            options={
                "verbose_name": "Auth identity",
                "verbose_name_plural": "Auth identities",
            },
        ),
        migrations.AddIndex(
            model_name="authidentity",
            index=models.Index(fields=["provider", "provider_user_id"], name="accounts_au_provide_d4f5ed_idx"),
        ),
        migrations.AddIndex(
            model_name="authidentity",
            index=models.Index(fields=["user", "provider"], name="accounts_au_user_id_7ea691_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="authidentity",
            unique_together={("provider", "provider_user_id")},
        ),
    ]
